name: Format Check

on: [push, pull_request]

jobs:
    gofmt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.23.1'

            - name: Check formatting
              run: |
                  if ! gofmt -l . | grep .; then
                    echo "Code is not properly formatted. Please run 'gofmt -w .' locally and commit the changes."
                    exit 1
                  fi
