name: Format Check

on: [push, pull_request]

jobs:
    gofmt:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: '1.23.1'

            - name: Run go fmt
              run: |
                  gofmt -w .
