name: Static Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Run Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      - name: Install statictest
        run: |
          # Assuming your static analyzer is in ./cmd/staticlint
          cd cmd/statictest
          go build -o statictest
          sudo mv statictest /usr/local/bin/

      - name: Run static analysis
        run: |
          statictest ./...
        continue-on-error: false

      # Optional: Add a step to comment on PR with findings
#      - name: Comment PR
#        if: github.event_name == 'pull_request'
#        uses: actions/github-script@v7
#        with:
#          script: |
#            const output = process.env.STATIC_ANALYSIS_OUTPUT
#            if (output) {
#              github.rest.issues.createComment({
#                issue_number: context.issue.number,
#                owner: context.repo.owner,
#                repo: context.repo.repo,
#                body: '### Static Analysis Results\n\n```\n' + output + '\n```'
#              })
#            }
#        env:
#          STATIC_ANALYSIS_OUTPUT: ${{ steps.static_analysis.outputs.output }}